"""Compare 2-point correlator G^(2)(r) in lambda phi^4 between NNFT and analytics.

Compares curves over a 1D radial grid r:
  - tree-level free propagator with UV regulator from asymptotic expansion
  - one-loop tadpole, no IR regulator via Schwinger parameterization
  - one-loop tadpole, with Gaussian IR vertex regulator via Schwinger parameterization
  - NNFT method A: free-theory sampling reweighted by exp(-S_int)
  - NNFT method B: Metropolis-Hastings on the modified PDF
  - NNFT method C: Hamiltonian Monte Carlo on the modified PDF
  - NNFT method D: MALA on the modified PDF
  - Lattice HMC (if matching data/lattice_g2_l{lambda}.npz is present,
    generated by lattice_correlators.py)

Saves data to data/lambda_phi4/compare_g2.npz and a plot to .../compare_g2.png.
"""

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import numpy as np

from nnft import (
    AnalFree,
    AnalPhi4,
    CosNetFT,
    HMCSampler,
    LambdaPhi4,
    MALASampler,
    MetropolisHastingsSampler,
    Theory,
)


# ---------- parameters ---------------------------------------------------

# Physics / NNFT model
d         = 2
m         = 1.0
lambda_   = 6.0
Lambda    = 100.0
regulator = "gaussian"
alpha     = 0
L         = 10.0
N         = 50

# Sample counts and batching
M_reweight = int(1e6)
M_mh       = int(1e4)   # MH samples after burn-in
M_hmc      = int(1e4)   # HMC samples after burn-in
M_mala     = int(5e3)   # MALA samples after burn-in
batch_size = 500        # field-sample chunk for memory control

# Metropolis-Hastings controls
mh_burn_in = 500
mh_thin    = 1
mh_W0_step = 1e-3
mh_b0_step = np.pi * 0.1
mh_proposal_mode = "all"

# HMC controls
hmc_burn_in = 500
hmc_thin = 1
hmc_n_leapfrog = 5
hmc_W0_step = 5e-4
hmc_b0_step = np.pi * 0.1

# MALA controls
mala_burn_in = 500
mala_thin = 1
mala_W0_tau = 1e-4
mala_b0_tau = np.pi * 0.1

# Interaction action / gradient evaluators
reweight_action_method = "real_space_mc"
reweight_M_x = 1024
action_method = "trans_sym"   # used by MH/HMC/MALA
momentum_eps = 1e-8

# Evaluation grid and output
# n_r    = 10
# r_grid = np.linspace(0.0, 3.0, n_r)
r_grid = np.array([0.0, 0.1, 0.2, 0.5, 1.0, 2.0, 3.0])
seed = 0
cache_analytics = True   # reuse analytical curves from prior .npz when params match
output_dir = Path("data/lambda_phi4")


# ---------- CLI overrides -------------------------------------------------
import argparse as _argparse
_p = _argparse.ArgumentParser(add_help=False)
_p.add_argument("--lambda", dest="_lambda_cli", type=float, default=None)
_p.add_argument("--suffix", dest="_suffix_cli", type=str, default=None)
_p.add_argument("--force", dest="_force_cli", action="store_true",
                help="ignore cached results and recompute everything")
_p.add_argument("--force-analytics", dest="_force_analytics_cli", action="store_true",
                help="recompute analytical curves only (keep cached NNFT samples)")
_p.add_argument("--force-rw", dest="_force_rw_cli", action="store_true")
_p.add_argument("--force-mh", dest="_force_mh_cli", action="store_true")
_p.add_argument("--force-hmc", dest="_force_hmc_cli", action="store_true")
_p.add_argument("--force-mala", dest="_force_mala_cli", action="store_true")
_cli, _ = _p.parse_known_args()
if _cli._lambda_cli is not None:
    lambda_ = _cli._lambda_cli
_suffix = _cli._suffix_cli if _cli._suffix_cli is not None else f"_l{lambda_}"
_force = _cli._force_cli
_force_analytics = _cli._force_analytics_cli or _force
_force_rw = _cli._force_rw_cli or _force
_force_mh = _cli._force_mh_cli or _force
_force_hmc = _cli._force_hmc_cli or _force
_force_mala = _cli._force_mala_cli or _force


# ---------- analytical curves ---------------------------------------------
def _sym_pair(r, d):
    """Symmetric placement x1 = (+r/2, 0, ..., 0), x2 = (-r/2, 0, ..., 0)."""
    x1 = np.r_[+r / 2.0, np.zeros(d - 1)]
    x2 = np.r_[-r / 2.0, np.zeros(d - 1)]
    return x1, x2


def analytical_curves(r_grid):
    free = AnalFree(d=d, m=m, Lambda=Lambda, regulator=regulator)
    phi4_no_ir = AnalPhi4(free, lambda_=lambda_, L=None)
    phi4_ir = AnalPhi4(free, lambda_=lambda_, L=L)

    # (1) tree, UV regulator -- asymptotic large-r form
    Delta_uv = np.array([
        free.G2(r, method="asymptotic_large_r") if r > 0.05 
        else free.G2(r, method="asymptotic_small_r") 
        for r in r_grid
    ])

    # (2) one-loop tadpole, no IR regulator -- Schwinger parameterization
    G2_one_loop_no_ir = np.array([
        phi4_no_ir.G2_one_loop(*_sym_pair(r, d), method="schwinger_t")
        for r in r_grid
    ])

    # (3) one-loop tadpole, Gaussian IR regulator -- Schwinger parameterization
    G2_one_loop_ir = np.array([
        phi4_ir.G2_one_loop(*_sym_pair(r, d), method="schwinger_t1t2")
        for r in r_grid
    ])
    return Delta_uv, G2_one_loop_no_ir, G2_one_loop_ir


# ---------- NNFT methods --------------------------------------------------
def x_points_for_grid(r_grid, d):
    """Construct evaluation points for each separation in ``r_grid``.

    For every ``r`` this returns the symmetric pair
    ``x1 = (+r/2, 0, ..., 0)`` and ``x2 = (-r/2, 0, ..., 0)``
    in a flattened array of shape ``(2 * len(r_grid), d)``.
    """
    r_arr = np.asarray(r_grid, dtype=float)
    pts = np.zeros((len(r_arr), 2, d))
    pts[:, 0, 0] = +r_arr / 2.0
    pts[:, 1, 0] = -r_arr / 2.0
    return pts.reshape(-1, d)


def nnft_reweighted(theory, phi4, r_grid, M, rng):
    x_points = x_points_for_grid(r_grid, theory.architecture.d_in)
    return theory.correlator_reweighted(
        x_points, M, rng,
        interaction=phi4,
        n_configs=len(r_grid),
        batch_size=batch_size,
        action_method=reweight_action_method,
        action_kwargs=_action_kwargs(reweight_action_method, reweight=True),
    )


def _action_kwargs(method, *, reweight=False):
    if method == "real_space_mc":
        if not reweight:
            raise ValueError("real_space_mc is configured only for reweighting here")
        return {"M_x": reweight_M_x}
    if method == "trans_sym":
        return {"eps": momentum_eps}
    return {}


def nnft_mh(theory, phi4, r_grid, M, rng):
    proposals = {
        "W0": ("normal", mh_W0_step),
        "b0": ("uniform_wrap", mh_b0_step),
        "W1": ("none", 0.0),
    }
    mh = MetropolisHastingsSampler(
        phi4, proposals,
        proposal_mode=mh_proposal_mode,
        burn_in=mh_burn_in, thin=mh_thin,
        action_method=action_method,
        action_kwargs=_action_kwargs(action_method),
    )
    x_points = x_points_for_grid(r_grid, theory.architecture.d_in)
    means, errs = theory.correlator(
        x_points, M, rng,
        sampler=mh, n_configs=len(r_grid),
    )
    return means, errs, mh.acceptance_rate


def nnft_hmc(theory, phi4, r_grid, M, rng):
    hmc = HMCSampler(
        phi4,
        step_size={"W0": hmc_W0_step, "b0": hmc_b0_step},
        n_leapfrog=hmc_n_leapfrog,
        burn_in=hmc_burn_in,
        thin=hmc_thin,
        action_method=action_method,
        action_kwargs=_action_kwargs(action_method),
    )
    x_points = x_points_for_grid(r_grid, theory.architecture.d_in)
    means, errs = theory.correlator(
        x_points, M, rng,
        sampler=hmc, n_configs=len(r_grid),
    )
    return means, errs, hmc.acceptance_rate


def nnft_mala(theory, phi4, r_grid, M, rng):
    mala = MALASampler(
        phi4,
        tau={"W0": mala_W0_tau, "b0": mala_b0_tau},
        burn_in=mala_burn_in,
        thin=mala_thin,
        action_method=action_method,
        action_kwargs=_action_kwargs(action_method),
    )
    x_points = x_points_for_grid(r_grid, theory.architecture.d_in)
    means, errs = theory.correlator(
        x_points, M, rng,
        sampler=mala, n_configs=len(r_grid),
    )
    return means, errs, mala.acceptance_rate


def _lattice_overlay_report(lz):
    """Return (blocking_reasons, warnings) for a loaded lattice npz file."""
    reasons = []
    warnings = []

    def has(key):
        return key in lz.files

    def close_key(key, expected, label=None):
        if not has(key):
            reasons.append(f"missing {key}")
            return
        if not np.isclose(float(lz[key]), float(expected)):
            name = label or key
            reasons.append(f"{name} mismatch: lattice={float(lz[key]):g}, expected={float(expected):g}")

    close_key("d", d)
    close_key("m", m)
    close_key("L", L)
    close_key("lambda_", lambda_, "lambda")
    if has("Lambda"):
        close_key("Lambda", Lambda)
    else:
        warnings.append("missing Lambda metadata; regenerate lattice file for UV checks")

    if has("observer"):
        observer = str(lz["observer"])
        if observer != "symmetric_interp":
            reasons.append(f"observer mismatch: lattice={observer}, expected=symmetric_interp")
    else:
        reasons.append("missing observer metadata; regenerate lattice file")

    if has("free_kernel"):
        free_kernel = str(lz["free_kernel"])
        if free_kernel == "local":
            warnings.append(
                "lattice used the local free kernel; use --free-kernel gaussian for the NNFT Gaussian UV kernel"
            )
        elif free_kernel != "gaussian":
            reasons.append(f"unknown lattice free_kernel={free_kernel}")
    else:
        warnings.append("missing free_kernel metadata; regenerate lattice file for UV-kernel checks")

    if has("r_grid") and len(lz["r_grid"]) == len(r_grid):
        if not np.allclose(lz["r_grid"], r_grid):
            warnings.append("lattice r_grid differs from NNFT r_grid; plotting at lattice r values")
    elif has("r_grid"):
        warnings.append("lattice r_grid length differs from NNFT r_grid; plotting at lattice r values")

    if has("uv_cutoff_over_Lambda"):
        ratio = float(lz["uv_cutoff_over_Lambda"])
        if ratio < 3.0:
            warnings.append(
                f"lattice pi/a is only {ratio:.3g} Lambda; UV cutoff effects may dominate"
            )
    if has("ir_edge_weight"):
        edge = float(lz["ir_edge_weight"])
        if edge > 1e-3:
            warnings.append(
                f"IR envelope at half box is {edge:.3e}; finite-volume effects may be visible"
            )
    if has("points_per_min_r"):
        ppr = float(lz["points_per_min_r"])
        if np.isfinite(ppr) and ppr < 2.0:
            warnings.append(
                f"shortest nonzero r has only {ppr:.3g} lattice spacings; short-r discretization may be large"
            )
    return reasons, warnings


# ---------- main ----------------------------------------------------------
def main():
    output_dir.mkdir(parents=True, exist_ok=True)
    arch = CosNetFT(d_in=d, m=m, alpha=alpha, Lambda=Lambda, regulator=regulator)
    th = Theory(arch, N=N, param_dists=arch.default_dists())
    phi4 = LambdaPhi4(lambda_, L, "gaussian")

    print(f"d={d}  m={m}  Lambda={Lambda}  regulator={regulator}  alpha={alpha}")
    print(f"L={L}  lambda={lambda_}  N={N}")
    print(
        f"M_reweight={M_reweight:.1e}  M_mh={M_mh}  "
        f"M_hmc={M_hmc}  M_mala={M_mala}  "
        f"proposal={mh_proposal_mode}"
    )
    print(
        f"S_int reweight={reweight_action_method}(M_x={reweight_M_x})  "
        f"MCMC={action_method}(eps={momentum_eps:g})"
    )
    print(f"r_grid = {r_grid}")
    print()

    cache_path = output_dir / f"compare_g2{_suffix}.npz"
    cached = None
    if cache_analytics and not _force and cache_path.exists():
        try:
            cached = np.load(cache_path, allow_pickle=True)
        except Exception:
            cached = None

    def _has(z, key):
        return z is not None and key in z.files

    def _match(z, key, val):
        return _has(z, key) and np.isclose(float(z[key]), float(val))

    def _match_str(z, key, val):
        return _has(z, key) and str(z[key]) == str(val)

    # Shared params controlling all three blocks
    shared_ok = (
        cached is not None
        and _match(cached, "d", d) and _match(cached, "m", m)
        and _match(cached, "Lambda", Lambda) and _match(cached, "alpha", alpha)
        and _match(cached, "L", L) and _match(cached, "lambda_", lambda_)
        and str(cached["regulator"]) == regulator
        and len(cached["r_grid"]) == len(r_grid)
        and np.allclose(cached["r_grid"], r_grid)
    )
    reuse_analytics = (not _force_analytics and shared_ok
        and all(_has(cached, k) for k in
            ("Delta_uv", "G2_one_loop_no_ir", "G2_one_loop_ir")))
    reuse_rw = (not _force_rw and shared_ok and _match(cached, "N", N)
                and _match(cached, "M_reweight", M_reweight)
                and _match_str(cached, "reweight_action_method", reweight_action_method)
                and _match(cached, "reweight_M_x", reweight_M_x)
                and _match(cached, "momentum_eps", momentum_eps)
                and _has(cached, "rw_mean") and _has(cached, "rw_err"))
    reuse_mh = (not _force_mh and shared_ok and _match(cached, "N", N)
                and _match(cached, "M_mh", M_mh)
                and _match(cached, "mh_burn_in", mh_burn_in)
                and _match(cached, "mh_thin", mh_thin)
                and _match(cached, "mh_W0_step", mh_W0_step)
                and _match(cached, "mh_b0_step", mh_b0_step)
                and _match_str(cached, "mh_proposal_mode", mh_proposal_mode)
                and _match_str(cached, "action_method", action_method)
                and _match(cached, "momentum_eps", momentum_eps)
                and _has(cached, "mh_mean") and _has(cached, "mh_err"))
    reuse_hmc = (not _force_hmc and shared_ok and _match(cached, "N", N)
                 and _match(cached, "M_hmc", M_hmc)
                 and _match(cached, "hmc_burn_in", hmc_burn_in)
                 and _match(cached, "hmc_thin", hmc_thin)
                 and _match(cached, "hmc_n_leapfrog", hmc_n_leapfrog)
                 and _match(cached, "hmc_W0_step", hmc_W0_step)
                 and _match(cached, "hmc_b0_step", hmc_b0_step)
                 and _match_str(cached, "action_method", action_method)
                 and _match(cached, "momentum_eps", momentum_eps)
                 and _has(cached, "hmc_mean") and _has(cached, "hmc_err"))
    reuse_mala = (not _force_mala and shared_ok and _match(cached, "N", N)
                  and _match(cached, "M_mala", M_mala)
                  and _match(cached, "mala_burn_in", mala_burn_in)
                  and _match(cached, "mala_thin", mala_thin)
                  and _match(cached, "mala_W0_tau", mala_W0_tau)
                  and _match(cached, "mala_b0_tau", mala_b0_tau)
                  and _match_str(cached, "action_method", action_method)
                  and _match(cached, "momentum_eps", momentum_eps)
                  and _has(cached, "mala_mean") and _has(cached, "mala_err"))

    # (1)+(2)+(3) analytical curves: tree-UV, one-loop no-IR, one-loop IR
    t_analytic = 0.0
    if reuse_analytics:
        print("reusing cached analytical curves.")
        Delta_uv = cached["Delta_uv"]
        G2_loop_no_ir = cached["G2_one_loop_no_ir"]
        G2_loop_ir = cached["G2_one_loop_ir"]
    else:
        print("computing analytical curves...")
        t0 = time.time()
        Delta_uv, G2_loop_no_ir, G2_loop_ir = analytical_curves(r_grid)
        t_analytic = time.time() - t0
        print(f"  done ({t_analytic:.1f}s)")

    # (4) NNFT method A: free-theory sampling, reweight by exp(-S_int)
    t_reweight = 0.0
    if reuse_rw:
        print(f"reusing cached NNFT reweight (M={int(cached['M_reweight']):.1e}).")
        rw_mean = cached["rw_mean"]
        rw_err = cached["rw_err"]
    else:
        print(f"NNFT method A: free-theory reweighting (M={M_reweight:.1e})...")
        t0 = time.time()
        rng = np.random.default_rng(seed)
        rw_mean, rw_err = nnft_reweighted(th, phi4, r_grid, M_reweight, rng)
        t_reweight = time.time() - t0
        print(f"  done ({t_reweight:.1f}s)")

    # (5) NNFT method B: Metropolis-Hastings on the modified PDF
    t_mh = 0.0
    acc = float("nan")
    if reuse_mh:
        print(f"reusing cached NNFT MH (steps={int(cached['M_mh'])}).")
        mh_mean = cached["mh_mean"]
        mh_err = cached["mh_err"]
        if _has(cached, "mh_acceptance"):
            acc = float(cached["mh_acceptance"])
    else:
        print(
            f"NNFT method B: Metropolis-Hastings "
            f"(steps={M_mh}, burn={mh_burn_in}, proposal={mh_proposal_mode})..."
        )
        t0 = time.time()
        rng = np.random.default_rng(seed + 100)
        mh_mean, mh_err, acc = nnft_mh(th, phi4, r_grid, M_mh, rng)
        t_mh = time.time() - t0
        print(f"  done ({t_mh:.1f}s)  acceptance = {acc:.3f}")

    # (6) NNFT method C: Hamiltonian Monte Carlo on the modified PDF
    t_hmc = 0.0
    hmc_acc = float("nan")
    if reuse_hmc:
        print(f"reusing cached NNFT HMC (steps={int(cached['M_hmc'])}).")
        hmc_mean = cached["hmc_mean"]
        hmc_err = cached["hmc_err"]
        if _has(cached, "hmc_acceptance"):
            hmc_acc = float(cached["hmc_acceptance"])
    else:
        print(
            f"NNFT method C: HMC "
            f"(steps={M_hmc}, burn={hmc_burn_in}, thin={hmc_thin}, "
            f"leapfrog={hmc_n_leapfrog})..."
        )
        t0 = time.time()
        rng = np.random.default_rng(seed + 200)
        hmc_mean, hmc_err, hmc_acc = nnft_hmc(th, phi4, r_grid, M_hmc, rng)
        t_hmc = time.time() - t0
        print(f"  done ({t_hmc:.1f}s)  acceptance = {hmc_acc:.3f}")

    # (7) NNFT method D: MALA on the modified PDF
    t_mala = 0.0
    mala_acc = float("nan")
    if reuse_mala:
        print(f"reusing cached NNFT MALA (steps={int(cached['M_mala'])}).")
        mala_mean = cached["mala_mean"]
        mala_err = cached["mala_err"]
        if _has(cached, "mala_acceptance"):
            mala_acc = float(cached["mala_acceptance"])
    else:
        print(
            f"NNFT method D: MALA "
            f"(steps={M_mala}, burn={mala_burn_in}, thin={mala_thin})..."
        )
        t0 = time.time()
        rng = np.random.default_rng(seed + 300)
        mala_mean, mala_err, mala_acc = nnft_mala(th, phi4, r_grid, M_mala, rng)
        t_mala = time.time() - t0
        print(f"  done ({t_mala:.1f}s)  acceptance = {mala_acc:.3f}")

    np.savez(
        output_dir / f"compare_g2{_suffix}.npz",
        r_grid=r_grid,
        Delta_uv=Delta_uv,
        G2_one_loop_no_ir=G2_loop_no_ir,
        G2_one_loop_ir=G2_loop_ir,
        rw_mean=rw_mean, rw_err=rw_err,
        mh_mean=mh_mean, mh_err=mh_err,
        hmc_mean=hmc_mean, hmc_err=hmc_err,
        mala_mean=mala_mean, mala_err=mala_err,
        d=d, m=m, Lambda=Lambda, regulator=regulator, alpha=alpha,
        L=L, lambda_=lambda_, N=N,
        M_reweight=M_reweight, M_mh=M_mh, M_hmc=M_hmc, M_mala=M_mala,
        reweight_action_method=reweight_action_method,
        reweight_M_x=reweight_M_x,
        mh_acceptance=acc, hmc_acceptance=hmc_acc, mala_acceptance=mala_acc,
        mh_burn_in=mh_burn_in, mh_thin=mh_thin,
        mh_W0_step=mh_W0_step, mh_b0_step=mh_b0_step,
        mh_proposal_mode=mh_proposal_mode,
        hmc_burn_in=hmc_burn_in, hmc_thin=hmc_thin,
        hmc_n_leapfrog=hmc_n_leapfrog,
        hmc_W0_step=hmc_W0_step, hmc_b0_step=hmc_b0_step,
        mala_burn_in=mala_burn_in, mala_thin=mala_thin,
        mala_W0_tau=mala_W0_tau, mala_b0_tau=mala_b0_tau,
        action_method=action_method, momentum_eps=momentum_eps,
    )

    print()
    print("=== timing summary ===")
    if t_analytic > 0:
        print(f"  analytics (3 curves, {len(r_grid)} r values): {t_analytic:.1f}s")
    if t_reweight > 0:
        print(
            f"  NNFT reweight (M={M_reweight:.1e}, "
            f"S={reweight_action_method}, M_x={reweight_M_x}): "
            f"{t_reweight:.1f}s -> {t_reweight / M_reweight * 1e6:.2f} us / sample"
        )
    else:
        print(f"  NNFT reweight: cached")
    if t_mh > 0:
        print(
            f"  NNFT MH       (steps={M_mh}, burn={mh_burn_in}, "
            f"proposal={mh_proposal_mode}): {t_mh:.1f}s "
            f"-> {t_mh / M_mh * 1e3:.2f} ms / step,  acc={acc:.3f}"
        )
    else:
        print(f"  NNFT MH: cached")
    if t_hmc > 0:
        print(
            f"  NNFT HMC      (steps={M_hmc}, burn={hmc_burn_in}, "
            f"L={hmc_n_leapfrog}): {t_hmc:.1f}s "
            f"-> {t_hmc / M_hmc * 1e3:.2f} ms / sample,  acc={hmc_acc:.3f}"
        )
    else:
        print(f"  NNFT HMC: cached")
    if t_mala > 0:
        print(
            f"  NNFT MALA     (steps={M_mala}, burn={mala_burn_in}): "
            f"{t_mala:.1f}s -> {t_mala / M_mala * 1e3:.2f} ms / sample, "
            f"acc={mala_acc:.3f}"
        )
    else:
        print(f"  NNFT MALA: cached")
    print()
    header = (
        f"{'r':>5}  {'Delta_uv':>10}  {'1-loop':>10}  {'1-loop IR':>10}  "
        f"{'reweight':>14}  {'MH':>14}  {'HMC':>14}  {'MALA':>14}"
    )
    print(header)
    print("-" * len(header))
    for i, r in enumerate(r_grid):
        print(
            f"{r:5.2f}  {Delta_uv[i]:10.4f}  {G2_loop_no_ir[i]:10.4f}  "
            f"{G2_loop_ir[i]:10.4f}  "
            f"{rw_mean[i]:7.4f}+/-{rw_err[i]:5.4f}  "
            f"{mh_mean[i]:7.4f}+/-{mh_err[i]:5.4f}  "
            f"{hmc_mean[i]:7.4f}+/-{hmc_err[i]:5.4f}  "
            f"{mala_mean[i]:7.4f}+/-{mala_err[i]:5.4f}"
        )

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(7, 5))
        # (1) tree, UV regulator
        ax.plot(r_grid, Delta_uv, "k-", label=r"tree, UV reg")
        # (2) one-loop, no IR regulator
        ax.plot(r_grid, G2_loop_no_ir, "C0-", label=r"1-loop, no IR")
        # (3) one-loop, Gaussian IR regulator
        ax.plot(r_grid, G2_loop_ir, "C1-", label=r"1-loop, Gaussian IR")
        # (4) NNFT method A: reweighting
        ax.errorbar(r_grid, rw_mean, yerr=rw_err, fmt="C2o",
                    label=f"NNFT reweight ({reweight_action_method}, M={M_reweight:.1e})",
                    capsize=3)
        # (5) NNFT method B: Metropolis-Hastings
        ax.errorbar(r_grid, mh_mean, yerr=mh_err, fmt="C3s",
                    label=f"NNFT MH ({mh_proposal_mode}, steps={M_mh})", capsize=3)
        # (6) NNFT method C: HMC
        ax.errorbar(r_grid, hmc_mean, yerr=hmc_err, fmt="C4^",
                    label=f"NNFT HMC (steps={M_hmc}, acc={hmc_acc:.2f})", capsize=3)
        # (7) NNFT method D: MALA
        ax.errorbar(r_grid, mala_mean, yerr=mala_err, fmt="C5v",
                    label=f"NNFT MALA (steps={M_mala}, acc={mala_acc:.2f})", capsize=3)

        # lattice HMC overlay (optional)
        lattice_path = output_dir / f"lattice_g2{_suffix}.npz"
        if lattice_path.exists():
            lz = np.load(lattice_path, allow_pickle=True)
            reasons, warnings = _lattice_overlay_report(lz)
            if reasons:
                print(f"(skipping {lattice_path.name}: {'; '.join(reasons)})")
            else:
                for warning in warnings:
                    print(f"(lattice warning: {warning})")
                block = int(lz["block_size"]) if "block_size" in lz.files else 1
                uv_cutoff = float(lz["uv_cutoff"]) if "uv_cutoff" in lz.files else np.pi / float(lz["a"])
                free_kernel = str(lz["free_kernel"]) if "free_kernel" in lz.files else "unknown"
                lat_label = (
                    f"lattice {str(lz['sampler'])} "
                    f"({free_kernel}, sym, a={float(lz['a']):.3g}, $N_L$={int(lz['N_L'])}, "
                    f"$\\pi/a$={uv_cutoff:.3g}, block={block})"
                )
                ax.errorbar(lz["r_grid"], lz["lat_mean"], yerr=lz["lat_err"],
                            fmt="C6D", label=lat_label, capsize=3)
        else:
            print(f"(no {lattice_path.name} found; skipping lattice overlay)")

        ax.set_xlabel("r")
        ax.set_ylabel(r"$G^{(2)}(r)$")
        ax.set_title(
            rf"$\lambda\phi^4$: $d={d}$, $m={m}$, $\Lambda={Lambda}$, "
            rf"$L={L}$, $\lambda={lambda_}$, $N={N}$"
        )
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)
        fig.tight_layout()
        out_png = output_dir / f"compare_g2{_suffix}.png"
        fig.savefig(out_png, dpi=140)
        print(f"\nplot saved to {out_png}")
    except ImportError:
        print("\nmatplotlib not available; skipped plotting.")


if __name__ == "__main__":
    main()
